# Generated by Django 4.2.10 on 2024-10-22 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule_medecin', models.CharField(max_length=50, unique=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soignemoiwebsite.administrateur')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('medicament_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('posologie', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('specialite_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Spécialité')),
            ],
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('sejour_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_entree', models.DateField(verbose_name="Date d'entrée")),
                ('date_sortie', models.DateField(verbose_name='Date de sortie')),
                ('motif', models.TextField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.medecin')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.specialite', verbose_name='Spécialité')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut_traitement', models.DateField()),
                ('date_fin_traitement', models.DateField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.medecin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.patient')),
            ],
        ),
        migrations.AddField(
            model_name='medecin',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.specialite'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('avis_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.medecin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.patient')),
            ],
            options={
                'verbose_name_plural': 'Avis',
            },
        ),
    ]
