# Generated by Django 4.2.10 on 2025-01-02 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_adresse'),
        ('soignemoiwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_secretaire', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customuser',),
        ),
        migrations.AddField(
            model_name='medicament',
            name='prescription',
            field=models.ManyToManyField(to='soignemoiwebsite.prescription'),
        ),
    ]
