# Generated by Django 4.2.10 on 2024-05-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soignemoiwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='medecin_id',
            new_name='medecin',
        ),
        migrations.RenameField(
            model_name='avis',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='medecin_id',
            new_name='medecin',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='specialite_id',
            new_name='specialite',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='medecin_id',
            new_name='medecin',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sejour',
            old_name='specialite_id',
            new_name='specialite',
        ),
        migrations.RenameField(
            model_name='sejour',
            old_name='user_id',
            new_name='user',
        ),
    ]
