# Generated by Django 4.2.10 on 2024-06-14 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soignemoiwebsite', '0002_rename_medecin_id_avis_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sejour',
            name='date_entree',
            field=models.DateField(verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='sejour',
            name='date_sortie',
            field=models.DateField(verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='sejour',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.specialite', verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='nom',
            field=models.CharField(max_length=50, unique=True, verbose_name='Spécialité'),
        ),
    ]
