# Generated by Django 4.2.10 on 2025-01-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soignemoiwebsite', '0002_secretaire_medicament_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='posologie',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='prescription',
        ),
        migrations.CreateModel(
            name='PrescriptionMedicament',
            fields=[
                ('prescriptionmedicament_id', models.AutoField(primary_key=True, serialize=False)),
                ('posologie', models.TextField(max_length=255)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.medicament')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soignemoiwebsite.prescription')),
            ],
        ),
    ]
