# Generated by Django 4.2.10 on 2024-06-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soignemoiwebsite', '0003_alter_sejour_date_entree_alter_sejour_date_sortie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Visiteur'},
        ),
    ]
