# Generated by Django 4.2.10 on 2024-10-25 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adresse',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Le prénom ne peut contenir que des lettres, espaces, apostrophes ou des tirets.', regex="^[A-Za-zÀ-ÖØ-öø-ÿ0-9'’,.\\s]+$")]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='genre',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nom',
            field=models.CharField(help_text='uniquement lettres, espaces, apostrophes ou des tirets.', max_length=50, validators=[django.core.validators.RegexValidator(message='Le prénom ne peut contenir que des lettres, espaces, apostrophes ou des tirets.', regex="^[A-Za-zÀ-ÖØ-öø-ÿ'’-]+(?: [A-Za-zÀ-ÖØ-öø-ÿ'’-]+)*$")]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prenom',
            field=models.CharField(help_text='uniquement lettres, espaces, apostrophes ou des tirets.', max_length=50, validators=[django.core.validators.RegexValidator(message='Le prénom ne peut contenir que des lettres, espaces, apostrophes ou des tirets.', regex="^[A-Za-zÀ-ÖØ-öø-ÿ'’-]+(?: [A-Za-zÀ-ÖØ-öø-ÿ'’-]+)*$")]),
        ),
    ]
