# Generated by Django 4.2.10 on 2024-10-26 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_adresse_alter_customuser_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adresse',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Mauvais format d'adresse", regex="^[A-Za-zÀ-ÖØ-öø-ÿ0-9'’,.\\s]+$")]),
        ),
    ]
