BEGIN;
--
-- Create model CustomUser
--
CREATE TABLE "accounts_customuser" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "genre" varchar(10) NOT NULL, "nom" varchar(50) NOT NULL, "prenom" varchar(50) NOT NULL, "adresse" varchar(100) NOT NULL, "email" varchar(50) NOT NULL UNIQUE, "is_active" boolean NOT NULL, "is_staff" boolean NOT NULL, "is_admin" boolean NOT NULL);
CREATE INDEX "accounts_customuser_email_4fd8e7ce_like" ON "accounts_customuser" ("email" varchar_pattern_ops);
COMMIT;

BEGIN;
--
-- Create model Administrateur
--
CREATE TABLE "soignemoiwebsite_administrateur" ("customuser_ptr_id" bigint NOT NULL UNIQUE, "admin_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY);
--
-- Create model Medecin
--
CREATE TABLE "soignemoiwebsite_medecin" ("customuser_ptr_id" bigint NOT NULL UNIQUE, "medecin_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "matricule_medecin" varchar(50) NOT NULL UNIQUE, "admin_id_id" integer NULL);
--
-- Create model Medicament
--
CREATE TABLE "soignemoiwebsite_medicament" ("medicament_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nom" varchar(50) NOT NULL, "posologie" text NOT NULL);
--
-- Create model Specialite
--
CREATE TABLE "soignemoiwebsite_specialite" ("specialite_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nom" varchar(50) NOT NULL UNIQUE);
--
-- Create model Utilisateur
--
CREATE TABLE "soignemoiwebsite_utilisateur" ("customuser_ptr_id" bigint NOT NULL UNIQUE, "user_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY);
--
-- Create model Sejour
--
CREATE TABLE "soignemoiwebsite_sejour" ("sejour_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_entree" date NOT NULL, "date_sortie" date NOT NULL, "motif" text NOT NULL, "specialite_id_id" integer NOT NULL, "user_id_id" integer NOT NULL);
--
-- Create model Prescription
--
CREATE TABLE "soignemoiwebsite_prescription" ("prescription_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_debut_traitement" date NOT NULL, "date_fin_traitement" date NOT NULL, "medecin_id_id" integer NOT NULL, "user_id_id" integer NOT NULL);
--
-- Add field specialite_id to medecin
--
ALTER TABLE "soignemoiwebsite_medecin" ADD COLUMN "specialite_id_id" integer NOT NULL CONSTRAINT "soignemoiwebsite_med_specialite_id_id_06dbe8f2_fk_soignemoi" REFERENCES "soignemoiwebsite_specialite"("specialite_id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "soignemoiwebsite_med_specialite_id_id_06dbe8f2_fk_soignemoi" IMMEDIATE;
--
-- Create model Intervention
--
CREATE TABLE "soignemoiwebsite_intervention" ("intervention_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "libelle_intervention" varchar(100) NOT NULL, "date_intervention" date NOT NULL, "medecin_id_id" integer NOT NULL, "user_id_id" integer NOT NULL);
--
-- Create model Avis
--
CREATE TABLE "soignemoiwebsite_avis" ("avis_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "libelle" varchar(255) NOT NULL, "date" date NOT NULL, "description" text NOT NULL, "medecin_id_id" integer NOT NULL, "user_id_id" integer NOT NULL);
ALTER TABLE "soignemoiwebsite_administrateur" ADD CONSTRAINT "soignemoiwebsite_adm_customuser_ptr_id_d7bc4015_fk_accounts_" FOREIGN KEY ("customuser_ptr_id") REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "soignemoiwebsite_medecin" ADD CONSTRAINT "soignemoiwebsite_med_customuser_ptr_id_607a40de_fk_accounts_" FOREIGN KEY ("customuser_ptr_id") REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "soignemoiwebsite_medecin" ADD CONSTRAINT "soignemoiwebsite_med_admin_id_id_c3f577a2_fk_soignemoi" FOREIGN KEY ("admin_id_id") REFERENCES "soignemoiwebsite_administrateur" ("admin_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "soignemoiwebsite_medecin_matricule_medecin_03bdd88e_like" ON "soignemoiwebsite_medecin" ("matricule_medecin" varchar_pattern_ops);
CREATE INDEX "soignemoiwebsite_medecin_admin_id_id_c3f577a2" ON "soignemoiwebsite_medecin" ("admin_id_id");
CREATE INDEX "soignemoiwebsite_specialite_nom_ccc65a88_like" ON "soignemoiwebsite_specialite" ("nom" varchar_pattern_ops);
ALTER TABLE "soignemoiwebsite_utilisateur" ADD CONSTRAINT "soignemoiwebsite_uti_customuser_ptr_id_68cd3b3e_fk_accounts_" FOREIGN KEY ("customuser_ptr_id") REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "soignemoiwebsite_sejour" ADD CONSTRAINT "soignemoiwebsite_sej_specialite_id_id_1064c2fe_fk_soignemoi" FOREIGN KEY ("specialite_id_id") REFERENCES "soignemoiwebsite_specialite" ("specialite_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "soignemoiwebsite_sejour" ADD CONSTRAINT "soignemoiwebsite_sej_user_id_id_209779f5_fk_soignemoi" FOREIGN KEY ("user_id_id") REFERENCES "soignemoiwebsite_utilisateur" ("user_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "soignemoiwebsite_sejour_specialite_id_id_1064c2fe" ON "soignemoiwebsite_sejour" ("specialite_id_id");
CREATE INDEX "soignemoiwebsite_sejour_user_id_id_209779f5" ON "soignemoiwebsite_sejour" ("user_id_id");
ALTER TABLE "soignemoiwebsite_prescription" ADD CONSTRAINT "soignemoiwebsite_pre_medecin_id_id_17faca37_fk_soignemoi" FOREIGN KEY ("medecin_id_id") REFERENCES "soignemoiwebsite_medecin" ("medecin_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "soignemoiwebsite_prescription" ADD CONSTRAINT "soignemoiwebsite_pre_user_id_id_57c9f976_fk_soignemoi" FOREIGN KEY ("user_id_id") REFERENCES "soignemoiwebsite_utilisateur" ("user_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "soignemoiwebsite_prescription_medecin_id_id_17faca37" ON "soignemoiwebsite_prescription" ("medecin_id_id");
CREATE INDEX "soignemoiwebsite_prescription_user_id_id_57c9f976" ON "soignemoiwebsite_prescription" ("user_id_id");
CREATE INDEX "soignemoiwebsite_medecin_specialite_id_id_06dbe8f2" ON "soignemoiwebsite_medecin" ("specialite_id_id");
ALTER TABLE "soignemoiwebsite_intervention" ADD CONSTRAINT "soignemoiwebsite_int_medecin_id_id_1bc9fd52_fk_soignemoi" FOREIGN KEY ("medecin_id_id") REFERENCES "soignemoiwebsite_medecin" ("medecin_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "soignemoiwebsite_intervention" ADD CONSTRAINT "soignemoiwebsite_int_user_id_id_874f8ce0_fk_soignemoi" FOREIGN KEY ("user_id_id") REFERENCES "soignemoiwebsite_utilisateur" ("user_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "soignemoiwebsite_intervention_medecin_id_id_1bc9fd52" ON "soignemoiwebsite_intervention" ("medecin_id_id");
CREATE INDEX "soignemoiwebsite_intervention_user_id_id_874f8ce0" ON "soignemoiwebsite_intervention" ("user_id_id");
ALTER TABLE "soignemoiwebsite_avis" ADD CONSTRAINT "soignemoiwebsite_avi_medecin_id_id_cea2afb0_fk_soignemoi" FOREIGN KEY ("medecin_id_id") REFERENCES "soignemoiwebsite_medecin" ("medecin_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "soignemoiwebsite_avis" ADD CONSTRAINT "soignemoiwebsite_avi_user_id_id_b631d891_fk_soignemoi" FOREIGN KEY ("user_id_id") REFERENCES "soignemoiwebsite_utilisateur" ("user_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "soignemoiwebsite_avis_medecin_id_id_cea2afb0" ON "soignemoiwebsite_avis" ("medecin_id_id");
CREATE INDEX "soignemoiwebsite_avis_user_id_id_b631d891" ON "soignemoiwebsite_avis" ("user_id_id");
COMMIT;


BEGIN;
--
-- Rename field medecin_id on avis to medecin
--
ALTER TABLE "soignemoiwebsite_avis" RENAME COLUMN "medecin_id_id" TO "medecin_id";
--
-- Rename field user_id on avis to user
--
ALTER TABLE "soignemoiwebsite_avis" RENAME COLUMN "user_id_id" TO "user_id";
--
-- Rename field medecin_id on intervention to medecin
--
ALTER TABLE "soignemoiwebsite_intervention" RENAME COLUMN "medecin_id_id" TO "medecin_id";
--
-- Rename field user_id on intervention to user
--
ALTER TABLE "soignemoiwebsite_intervention" RENAME COLUMN "user_id_id" TO "user_id";
--
-- Rename field admin_id on medecin to admin
--
ALTER TABLE "soignemoiwebsite_medecin" RENAME COLUMN "admin_id_id" TO "admin_id";
--
-- Rename field specialite_id on medecin to specialite
--
ALTER TABLE "soignemoiwebsite_medecin" RENAME COLUMN "specialite_id_id" TO "specialite_id";
--
-- Rename field medecin_id on prescription to medecin
--
ALTER TABLE "soignemoiwebsite_prescription" RENAME COLUMN "medecin_id_id" TO "medecin_id";
--
-- Rename field user_id on prescription to user
--
ALTER TABLE "soignemoiwebsite_prescription" RENAME COLUMN "user_id_id" TO "user_id";
--
-- Rename field specialite_id on sejour to specialite
--
ALTER TABLE "soignemoiwebsite_sejour" RENAME COLUMN "specialite_id_id" TO "specialite_id";
--
-- Rename field user_id on sejour to user
--
ALTER TABLE "soignemoiwebsite_sejour" RENAME COLUMN "user_id_id" TO "user_id";
COMMIT;
